const FamiliaEquipos = [
    { value: '', label: 'ABRAZADERA GIRATORIA DALMINE' },
    { value: '', label: 'AJUSTE CIRCULAR DE 40X50' },
    { value: '', label: 'AJUSTE DE 10 X 30' },
    { value: '', label: 'AJUSTE DE 10 X 40' },
    { value: '', label: 'AJUSTE DE 10 X 60' },
    { value: '', label: 'AJUSTE DE 10 X 80' },
    { value: '', label: 'AJUSTE DE 15 X 60' },
    { value: '', label: 'AJUSTE DE 20 X 30' },
    { value: '', label: 'AJUSTE DE 20 X 40' },
    { value: '', label: 'AJUSTE DE 20 X 60' },
    { value: '', label: 'AJUSTE DE 25 X 40' },
    { value: '', label: 'AJUSTE DE 25 X 60' },
    { value: '', label: 'AJUSTE DE 30 X 40' },
    { value: '', label: 'AJUSTE DE 30 X 60' },
    { value: '', label: 'AJUSTE DE 35 X 60' },
    { value: '', label: 'AJUSTE DE 40 X 40' },
    { value: '', label: 'AJUSTE DE 40 X 60' },
    { value: '', label: 'AJUSTE DE 45 X 60' },
    { value: '', label: 'AJUSTE DE 50 X 60' },
    { value: '', label: 'AJUSTE DE 50 X 80' },
    { value: '', label: 'AJUSTE DE 60 X 60' },
    { value: '', label: 'ALINEADOR DE 1,00' },
    { value: '', label: 'ALINEADOR DE 1,25' },
    { value: '', label: 'ALINEADOR DE 1,50' },
    { value: '', label: 'ALINEADOR DE 1,75' },
    { value: '', label: 'ALINEADOR DE 1,80' },
    { value: '', label: 'ALINEADOR DE 2,00' },
    { value: '', label: 'ALINEADOR DE 2,45' },
    { value: '', label: 'ALINEADOR DE 2,82' },
    { value: '', label: 'ALINEADOR DE 3,00' },
    { value: '', label: 'ALINEADOR DE 4,00' },
    { value: '', label: 'ALINEADOR DE 6,00' },
    { value: '', label: 'ALLANADORA' },
    { value: '', label: 'ALMADANA DE 12/14/ 16 LIBRAS' },
    { value: '', label: 'ANDAMIO COLGANTE' },
    { value: '', label: 'ANDAMIO MULTIPERSONAL' },
    { value: '', label: 'ANGULO DE 0,50' },
    { value: '', label: 'ANGULO DE 0,55' },
    { value: '', label: 'ANGULO DE 0,60' },
    { value: '', label: 'ANGULO DE 0,70' },
    { value: '', label: 'ANGULO DE 1,20' },
    { value: '', label: 'ARNES DE SEGURIDAD' },
    { value: '', label: 'ASPAS PARA ALLANADORAS' },
    { value: '', label: 'ASPIRADORA INDUSTRIAL' },
    { value: '', label: 'BALDE PARA MOLINETE' },
    { value: '', label: 'BALDE PARA PLUMA' },
    { value: '', label: 'BALISAS PARA SEÑALIZACION' },
    { value: '', label: 'BARRA' },
    { value: '', label: 'BASCULA 500 KG + PESAS' },
    { value: '', label: 'BASE COLLARIN' },
    { value: '', label: 'BASE PARA PLUMA' },
    { value: '', label: 'BASE SENCILLA ANDAMIO DE CARGA' },
    { value: '', label: 'BASTON PRA CILINDRO MH' },
    { value: '', label: 'BISELES PARA FORMALETA' },
    { value: '', label: 'BOMBA HIDROSTATICA' },
    { value: '', label: 'BRIDA PULIDORA' },
    { value: '', label: 'BRILLADORA DE PISO ELECTRICA A 110 VTS' },
    { value: '', label: 'BROCA 1 1/4 SDS MAX ESTRIADA' },
    { value: '', label: 'BROCA 1 1/8 SDS MAX' },
    { value: '', label: 'BROCA 1 7/16' },
    { value: '', label: 'BROCA 1/2 A 5/8 SDS PLUS' },
    { value: '', label: 'BROCA 1/4 SDS PLUS' },
    { value: '', label: 'BROCA 3/16 SDS PLUS' },
    { value: '', label: 'BROCA 3/4 SDS PLUS' },
    { value: '', label: 'BROCA 3/8 SDS PLUS' },
    { value: '', label: 'BROCA 5/16 SDS PLUS' },
    { value: '', label: 'BROCA 5/8 SDS PLUS' },
    { value: '', label: 'BROCA 7/8 SDS MAX' },
    { value: '', label: 'BROCA 7/8 SDS PLUS' },
    { value: '', label: 'BROCA DE 1/2 SDS PLUS' },
    { value: '', label: 'BROCAS SDS MAX 5/8 A 1' },
    { value: '', label: 'BUZARDA PARA TALADRO' },
    { value: '', label: 'CAN METALICO PARA ANDAMIO TIJERA' },
    { value: '', label: 'CANES MADERA 2,50 A 3,00 MTS' },
    { value: '', label: 'CARETA PARA SOLDADOR' },
    { value: '', label: 'CARGUERA DE 3,00 MTS' },
    { value: '', label: 'CARGUERA DE 4,00 MTS' },
    { value: '', label: 'CARRITO PARA CORTADORA DE ADOBE' },
    { value: '', label: 'CARRITO PARA VIBROCOMPACTADOR RANA' },
    { value: '', label: 'CASCO DE PROTECCION' },
    { value: '', label: 'CERCHAS METALICAS DE 1,50 MTS' },
    { value: '', label: 'CERCHAS METALICAS DE 3,00 MTS' },
    { value: '', label: 'CHAPETA TENSORA' },
    { value: '', label: 'CILINDRO MANHOLE DE 1,20 MTS' },
    { value: '', label: 'CILINDRO MUESTRA CONCRETO' },
    { value: '', label: 'CILINDRO MUESTRA DE CONCRETO MEDIANO' },
    { value: '', label: 'CILINDRO MUESTRA DE CONCRETO PEQUEÑO' },
    { value: '', label: 'CINCEL PALA ANCHA DEMOLEDOR PISO' },
    { value: '', label: 'CINCEL PARA MARTILLO DEMOLEDOR' },
    { value: '', label: 'CINCEL PARA MARTILLO NEUMATICO' },
    { value: '', label: 'CINCEL PARA TALADRO DEMOLEDOR' },
    { value: '', label: 'CINCEL SDS PLUS ROTOPERCUTOR' },
    { value: '', label: 'CIZALLA' },
    { value: '', label: 'CIZALLA SATA 36' },
    { value: '', label: 'CLAVIJA A 220 PARA EXTENSION' },
    { value: '', label: 'CLAVIJA A 220 PARA PLANTA' },
    { value: '', label: 'COBRO MOVIMIENTO DE TIERRA POR METROS CUBICOS' },
    { value: '', label: 'COBRO PISTOLA DE IMPACTO' },
    { value: '', label: 'COBRO RETROACTIVO' },
    { value: '', label: 'COCHE LLANTA NEUMATICA' },
    { value: '', label: 'CODAL DE 3 MTS' },
    { value: '', label: 'COMPRESOR DE AIRE DE 300 LBS' },
    { value: '', label: 'COMPRESOR DE PINTURA 100 LBS' },
    { value: '', label: 'COMPRESOR DEMOLEDOR X HORAS' },
    { value: '', label: 'CONCRETADORA 0,5 SACOS' },
    { value: '', label: 'CONCRETADORA 1,5 SACOS' },
    { value: '', label: 'CONCRETADORA 2,0 SACOS' },
    { value: '', label: 'CONO DE 1,20 PARA MANHOLE EXTERNO' },
    { value: '', label: 'CONO DE 1,20 PARA MANHOLE INTERNO' },
    { value: '', label: 'CONO SLUMP + VARILLA' },
    { value: '', label: 'CONOS PARA SEÑALIZACION' },
    { value: '', label: 'COPA SIERRA PARA META DE 25 MM' },
    { value: '', label: 'CORTADORA ADOBE ELECTRICA 220 V' },
    { value: '', label: 'CORTADORA BALDOSIN DE 0,60' },
    { value: '', label: 'CORTADORA BALDOSIN DE 0,90' },
    { value: '', label: 'CORTADORA DE PISO' },
    { value: '', label: 'CORTADORA DE PISO CON OPERARIO POR M/L' },
    { value: '', label: 'CUELLO 1,20 MANHOLE EXTERNO' },
    { value: '', label: 'CUELLO 1,20 MANHOLE INTERNO' },
    { value: '', label: 'CUÑAS LISAS PARA FORMALETA' },
    { value: '', label: 'CUÑAS PERFORADAS PARA FORMALETA' },
    { value: '', label: 'DIAGONAL DE 2,06' },
    { value: '', label: 'DIAGONAL DE 2,10' },
    { value: '', label: 'DIAGONAL DE 2,40' },
    { value: '', label: 'DIAGONAL DE 2,50' },
    { value: '', label: 'DIAGONAL DE 2,81' },
    { value: '', label: 'DIAGONAL DE 3,00' },
    { value: '', label: 'DIAGONAL DE 3,50' },
    { value: '', label: 'DIAGONAL PARA ANDAMIO DE CARGA' },
    { value: '', label: 'DIFERENCIAL DE 1 TONELADA' },
    { value: '', label: 'DIFERENCIAL DE 2 TONELADAS' },
    { value: '', label: 'DISCO DIAMANTE 4' },
    { value: '', label: 'DISCO DIAMANTE 7/9 PARA PULIDORA' },
    { value: '', label: 'DISCO DIAMANTE PARA CORTADORA PISO' },
    { value: '', label: 'DISCO DIAMANTE PARA CORTE DE ADOBE' },
    { value: '', label: 'DISCO TUNGSTENO PARA SIERRA' },
    { value: '', label: 'DISCOS DE CORTE 4' },
    { value: '', label: 'DISCOS DE CORTE 9' },
    { value: '', label: 'DISCOS DE PULIR 4' },
    { value: '', label: 'DISCOS DE PULIR 9' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,10' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,15' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,20' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,25' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,30' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,35' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,40' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,50' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,55' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,60' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,65' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,70' },
    { value: '', label: 'DISTANCIADOR MURO DE 0,90' },
    { value: '', label: 'EJE DE PLUMA' },
    { value: '', label: 'ENDEREZADOR DE VARILLA' },
    { value: '', label: 'EQUIPO DE OXICORTE' },
    { value: '', label: 'EQUIPO ESPAñOL X M/2' },
    { value: '', label: 'ESCALERA DE MADERA POR CUERPO' },
    { value: '', label: 'ESCALERA DE TIJERA EN ALUMINIO DE 1,50 MTS' },
    { value: '', label: 'ESCALERA DE TIJERA EN ALUMINIO DE 1.80 MTS' },
    { value: '', label: 'ESCALERA DE TIJERA EN ALUMINIO DE 2,00 MTS' },
    { value: '', label: 'ESCALERA DE TIJERA EN ALUMINIO DE 2,50 MTS' },
    { value: '', label: 'ESCALERA DE TIJERA EN ALUMINIO DE 3,00 MTS' },
    { value: '', label: 'ESCALERA DE TIJERA EN ALUMINIO DE 4,00 MTS' },
    { value: '', label: 'ESCALERA DIELECTRICA 2 CUERPOS 10,00 MTS' },
    { value: '', label: 'ESCALERA DIELECTRICA 2 CUERPOS 12,00 MTS' },
    { value: '', label: 'ESCALERA DIELECTRICA 2 CUERPOS 7,00 MTS' },
    { value: '', label: 'ESCALERA DIELECTRICA 2 CUERPOS 8,00 MTS' },
    { value: '', label: 'ESCALERA DIELECTRICA 2 CUERPOS 9,50 MTS' },
    { value: '', label: 'ESCALERA GATO DE 2000*300MM' },
    { value: '', label: 'ESCALERA INTERNA ANDAMIO MULTIDIRECCIONAL DE 2.25 MTS' },
    { value: '', label: 'ESCALERA VERTICAL DE 3,00 MTS' },
    { value: '', label: 'ESCALERAS INTERNAS PARA ANDAMIO DE TIJERA' },
    { value: '', label: 'ESTIBADORA' },
    { value: '', label: 'EXTENSION 3*8' },
    { value: '', label: 'EXTENSIONES ENCAUCHETADAS 2*10-2*12' },
    { value: '', label: 'EXTRACTOR DE AIRE A 110 VOLTIOS' },
    { value: '', label: 'FORMALETA CIRCULAR DE 0,40 X 2,40 MTS' },
    { value: '', label: 'FORMALETA CIRCULAR DE 0,40 X 3,00 MTS' },
    { value: '', label: 'FORMALETA CIRCULAR DE 0.80 X 2,20 MTS' },
    { value: '', label: 'FORMALETA CIRCULAR DE 0.80 X 3,00 MTS' },
    { value: '', label: 'FORMALETA DE COLUMNA DE 0,30 X 2,40 MTS' },
    { value: '', label: 'FORMALETA DE COLUMNA DE 0,40 X 2,40 MTS' },
    { value: '', label: 'FORMALETA DE COLUMNA DE 0,50 X 2,40 MTS' },
    { value: '', label: 'FUMIGADORA 20 LBS' },
    { value: '', label: 'GANCHO EN U PARA CILINDRO MH' },
    { value: '', label: 'GARRA TENSORA' },
    { value: '', label: 'GATO HIDRAULICO MANUAL PEQUEÑO' },
    { value: '', label: 'GATO TENSOR' },
    { value: '', label: 'GRAPA FORMALETA' },
    { value: '', label: 'GRILLETES PARA ANDAMIO COLGANTE' },
    { value: '', label: 'GUARDA CONCRETADORA' },
    { value: '', label: 'GUARDA PULIDORA' },
    { value: '', label: 'HACHA' },
    { value: '', label: 'HIDROLAVADORA ELECTRICA A 110 VOLTIOS' },
    { value: '', label: 'HIDROLAVADORA ELECTRICA A 220 VOLTIOS' },
    { value: '', label: 'HONORARIOS POR ADMINISTRACIÓN' },
    { value: '', label: 'HORIZONTAL DE 0,70 MTS' },
    { value: '', label: 'HORIZONTAL DE 1,40 MTS' },
    { value: '', label: 'HORIZONTAL DE 1,50 MTS' },
    { value: '', label: 'HORIZONTAL DE 2,00 MTS' },
    { value: '', label: 'HORIZONTAL DE 2,25 MTS' },
    { value: '', label: 'HORIZONTAL DE 3,00 MTS' },
    { value: '', label: 'HORIZONTAL DE 3,00 MTS TIPO CERCHA' },
    { value: '', label: 'LIJADORA DE MADERA' },
    { value: '', label: 'LINEA DE VIDA' },
    { value: '', label: 'LLAVE DE EXPANSION' },
    { value: '', label: 'LLAVE DE TUBO 36' },
    { value: '', label: 'LLAVE DE TUBO DE 14' },
    { value: '', label: 'LLAVE DE TUBO DE 24' },
    { value: '', label: 'LLAVE DISCO PULIDORA' },
    { value: '', label: 'MANDRIL PORTA BROCAS' },
    { value: '', label: 'MANGO PARA TALADRO ROTOPERCUTOR' },
    { value: '', label: 'MANGO PULIDORA' },
    { value: '', label: 'MANGO TALADRO DEMOLEDOR DE MURO' },
    { value: '', label: 'MANGUERA DE SUCCION CON GRANADA * M/L' },
    { value: '', label: 'MANGUERA JARDINERA' },
    { value: '', label: 'MANGUERA PLANA 2 * M/L' },
    { value: '', label: 'MANILA DE POLIPROPILENO' },
    { value: '', label: 'MARCO DE ANDAMIO DE 1,20 X 1,50 MTS' },
    { value: '', label: 'MARCO DE ANDAMIO DE 1,50 X 1,50 MTS' },
    { value: '', label: 'MARCO TRIANGULAR 1,00 X 1,50' },
    { value: '', label: 'MARTILLO DE PISO DEWALT' },
    { value: '', label: 'MARTILLO DEMOLEDOR DE PISO MAKITA' },
    { value: '', label: 'MELLIZAS 3.00 A 3.50 MT' },
    { value: '', label: 'MEZCLERO' },
    { value: '', label: 'MOLDE TRIPLE PARA CUBOS CEMENTO Y MORTERO EN ACERO' },
    { value: '', label: 'MOLINETES' },
    { value: '', label: 'MOTOBOMBA GASOLINA ESTACIONARIA' },
    { value: '', label: 'MOTOR A GASOLINA' },
    { value: '', label: 'MOTOR DIESEL' },
    { value: '', label: 'MOTOR ELECTRICO A 220 VTS' },
    { value: '', label: 'MUELA PARA MARTILLO DEMOLEDOR' },
    { value: '', label: 'MUELA PARA MARTILLO NEUMATICO' },
    { value: '', label: 'MUELA PARA TALADRO DEMOLEDOR' },
    { value: '', label: 'MUELA SDS PLUS ROTOPERCUTOR' },
    { value: '', label: 'PALA' },
    { value: '', label: 'PALA PARA MARTILLO DEMOLEDOR DE PISO' },
    { value: '', label: 'PESA DE 100 KGS' },
    { value: '', label: 'PESA DE 200 KGS' },
    { value: '', label: 'PESA DE 50 KGS' },
    { value: '', label: 'PESCA' },
    { value: '', label: 'PICA' },
    { value: '', label: 'PIEDRA PARA PULIR' },
    { value: '', label: 'PINES DOBLES' },
    { value: '', label: 'PIPETA DE GAS + SOPLETE' },
    { value: '', label: 'PIPETAS DE GAS E HIDROGENO' },
    { value: '', label: 'PISON' },
    { value: '', label: 'PISTOLA DE CALEFATEO' },
    { value: '', label: 'PISTOLA PARA COMPRESOR DE AIRE' },
    { value: '', label: 'PISTOLA PARA HIDROLAVADORA + MANGUERA' },
    { value: '', label: 'PIVOTES' },
    { value: '', label: 'PLANTA GENERADORA DE ENERGIA DIESEL 50KVA' },
    { value: '', label: 'PLATAFORMA DE 0.60 X 3.00 MTS' },
    { value: '', label: 'PLATAFORMA DE 1,40 MTS' },
    { value: '', label: 'PLATAFORMA DE 1,50 MTS' },
    { value: '', label: 'PLATAFORMA DE 2,00 MTS' },
    { value: '', label: 'PLATAFORMA DE ANDAMIO MULTIPERSONAL' },
    { value: '', label: 'PLATAFORMA DE SEGURIDAD 0.23*1.50 MTS' },
    { value: '', label: 'PLATAFORMA DE SEGURIDAD 0.30*2.25 MTS' },
    { value: '', label: 'PLATAFORMA DE SEGURIDAD 0.32*3.00 MTS' },
    { value: '', label: 'PLATINA PARA ESTRIBOS' },
    { value: '', label: 'PLATO FLOTANTE PARA ALLANADORA' },
    { value: '', label: 'PLUMA DE 2,50 A 3,00 KG DE 60 *80 MTS' },
    { value: '', label: 'POLEA 1 CANAL' },
    { value: '', label: 'POLEA 2 CANALES' },
    { value: '', label: 'POLICHADORA' },
    { value: '', label: 'PONCHADORA' },
    { value: '', label: 'PULIDORA DE 4 MAKITA' },
    { value: '', label: 'PULIDORA INDUSTRIAL 110 VTS DB' },
    { value: '', label: 'PULIDORA INDUSTRIAL 110 VTS MAKITA' },
    { value: '', label: 'PUNTAL INDE-K 3M' },
    { value: '', label: 'PUNTAL INDE-K 4.20 MT' },
    { value: '', label: 'PUNTERO SDS PLUS' },
    { value: '', label: 'REFLECTOR A 110 VTS' },
    { value: '', label: 'REFLECTOR ELECTRICO 220 VTS' },
    { value: '', label: 'REPARACION DE PULIDORA INDUSTRIAL' },
    { value: '', label: 'REPARACION PLUMA GRUA' },
    { value: '', label: 'RINCONERAS DE 0,10 X 0,10 X 0,60' },
    { value: '', label: 'RINCONERAS DE 0,10 X 0,10 X 1,20' },
    { value: '', label: 'RINCONERAS DE 0,20 X 0,20 X 1,20' },
    { value: '', label: 'RINCONERAS DE 0.10 X 0.10 X 0.70' },
    { value: '', label: 'RIOSTRA INFERIOR' },
    { value: '', label: 'RIOSTRA PARA ANDAMIO DE CARGA' },
    { value: '', label: 'RUEDAS PARA ANDAMIO DE TIJERA' },
    { value: '', label: 'RUEDAS PARA ANDAMIO MULTIDIRECCIONAL' },
    { value: '', label: 'SERVICIO DE TRANSPORTE' },
    { value: '', label: 'SERVICIO TECNICO' },
    { value: '', label: 'SIERRA CIRCULAR' },
    { value: '', label: 'SIERRA CIRCULAR MAKITA' },
    { value: '', label: 'SLINGA' },
    { value: '', label: 'SOLDADOR ULTRA WEE A 220 V' },
    { value: '', label: 'SOPLADORA MAKITA' },
    { value: '', label: 'TABLERO DE 10 X 100' },
    { value: '', label: 'TABLERO DE 10 X 120' },
    { value: '', label: 'TABLERO DE 15 X 120' },
    { value: '', label: 'TABLERO DE 20 X 120' },
    { value: '', label: 'TABLERO DE 25 X 120' },
    { value: '', label: 'TABLERO DE 30 X 120' },
    { value: '', label: 'TABLERO DE 40 X 120' },
    { value: '', label: 'TABLERO DE 45 X 120' },
    { value: '', label: 'TABLERO DE 50 X 120' },
    { value: '', label: 'TABLERO DE 60 X 100' },
    { value: '', label: 'TABLERO DE 60 X 120' },
    { value: '', label: 'TABLERO TRICAPA DE 1.0 X 0.50 MT' },
    { value: '', label: 'TACO METALICO DE 1,80 A 2,80 MTS' },
    { value: '', label: 'TACO METALICO DE 2,00 A 3,30 MTS' },
    { value: '', label: 'TACO METALICO DE 4,20 MTS' },
    { value: '', label: 'TACO METALICO DE 5,00 A 5,50 MTS' },
    { value: '', label: 'TACO METALICO ENANO DE 1,00 MT A 1,50 MT' },
    { value: '', label: 'TACO METALICO HALADOR' },
    { value: '', label: 'TALADRO DEMOLEDOR DE MURO MAKITA' },
    { value: '', label: 'TALADRO ROTOPERCUTOR BOSCH' },
    { value: '', label: 'TALADRO ROTOPERCUTOR MAKITA' },
    { value: '', label: 'TELERA DE 0,45 X 1,35' },
    { value: '', label: 'TELERA DE 0,90 X 1,35' },
    { value: '', label: 'TENSOR EN 3/8 PARA FORMALETA' },
    { value: '', label: 'TENSORES' },
    { value: '', label: 'TIFO' },
    { value: '', label: 'TIJERAS DE 2,00 MTS PARA ANDAMIO' },
    { value: '', label: 'TIJERAS DE 2,50 MTS PARA ANDAMIO' },
    { value: '', label: 'TIRO DE ARRASTRE PARA MEZCLADORA' },
    { value: '', label: 'TORNILLO EN U' },
    { value: '', label: 'TORNILLO NIVELADOR' },
    { value: '', label: 'TRONZADORA' },
    { value: '', label: 'TUBO DALMINE 42MM 2,00 MTS' },
    { value: '', label: 'TUBO DALMINE 42MM 3,00 MTS' },
    { value: '', label: 'TUBO DALMINE 42MM 4,00 MTS' },
    { value: '', label: 'TUBO DALMINE 42MM 6,00 MTS' },
    { value: '', label: 'TUBO PTS 10 X 10 X 2,00 MTS' },
    { value: '', label: 'TUBO PTS 10 X 10 X 3,00 MTS' },
    { value: '', label: 'TUBO PTS DE 10 X 10 X 2,50 MTS' },
    { value: '', label: 'TUBOS' },
    { value: '', label: 'UÑAS' },
    { value: '', label: 'VARILLA PARA CONO SLUMP' },
    { value: '', label: 'VENTA DE CABLE PARA PLUMA GRUA' },
    { value: '', label: 'VENTA DE CAJA DE BALAS' },
    { value: '', label: 'VENTA DE CILINDROS DE MUESTRA DE CONCRETO' },
    { value: '', label: 'VENTA DE CIZALLA' },
    { value: '', label: 'VENTA DE COCHE' },
    { value: '', label: 'VENTA DE COMPRESOR DEMOLEDOR X HORAS REC DOMINICALES-FESTIVOS Y/O NOCTURNO' },
    { value: '', label: 'VENTA DE DESTAQUIADOR PARA TUBERIA X HORA' },
    { value: '', label: 'VENTA DE DISCOS DE CORTE' },
    { value: '', label: 'VENTA DE DISTANCIADORES' },
    { value: '', label: 'VENTA DE EQUIPO USADO' },
    { value: '', label: 'VENTA DE EXTENSION ENCAUCHETADA POR METRO' },
    { value: '', label: 'VENTA DE FILTRO DE AIRE' },
    { value: '', label: 'VENTA DE HOJA SUPER T DE 153*254*19 MM' },
    { value: '', label: 'VENTA DE INSUMOS' },
    { value: '', label: 'VENTA DE INSUMOS SIN IVA' },
    { value: '', label: 'VENTA DE JUEGO DE ASPAS' },
    { value: '', label: 'VENTA DE MEZCLADORA DE SEGUNDA' },
    { value: '', label: 'VENTA DE MINI BREACKE DE CORTADORA DE ADOBE' },
    { value: '', label: 'VENTA DE MINICARGADOR BOBCAT X HORAS' },
    { value: '', label: 'VENTA DE PESA PARA BASCULA 200 GK' },
    { value: '', label: 'VENTA DE PLASTICO POR METRO' },
    { value: '', label: 'VENTA DE POLEA' },
    { value: '', label: 'VENTA DE REPUESTOS VARIOS' },
    { value: '', label: 'VENTA DE RODILLO COMPACTADOR POR HORA CON OPERARIO + COMBUSTIBLE' },
    { value: '', label: 'VENTA DE TUERCA O CHAPOLA PARA ANDAMIO' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE ACEITE' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE ACPM POR GALON' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE BANDAS TIPO INDUSTRIAL' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE CINTA PARA SEÑALIZACION' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE FORMALETA DE COLUMNA DE 0.50 X 240' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE GASOLINA POR GALON' },
    { value: '', label: 'VENTA Y/O SUMINISTRO DE GRAPAS FORMALETA' },
    { value: '', label: 'VERTICAL DE 0,50' },
    { value: '', label: 'VERTICAL DE 1,00' },
    { value: '', label: 'VERTICAL DE 1,50' },
    { value: '', label: 'VERTICAL DE 2,00' },
    { value: '', label: 'VIBRADOR ELECTRICO CABEZOTE' },
    { value: '', label: 'VIBRADOR ELECTRICO TIPO AGUJA WYCO A 110 V' },
    { value: '', label: 'VIBRADOR ELECTRICO WYCO 110 V TIPO CABEZOTE' },
    { value: '', label: 'VIBROCOMPACTADOR 4 TIEMP RANA A GASOLINA' },
    { value: '', label: 'VIBROCOMPACTADOR CANGURO A GASOLINA MASALTA' },
    { value: '', label: 'ZORRA DE TRANSPORTE' },
];
export default FamiliaEquipos;